nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: Une API permettant de récupérer des artistes et des événements"
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api
